### ISSUE TITLE
Strasny error po dakych commandoch cez discord

### ISSUE THREAD

**Issue by tsrubar** [fusion2222/recorder_discord_bot#3]
```Ignoring exception in on_message
Traceback (most recent call last):
  File "/root/mato/recorder_discord_bot/.venv/lib/python3.6/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 140, in on_message
    await self.write_countdown_msg(None, text_channel, voice_client, True)
  File "./bot.py", line 83, in write_countdown_msg
    dirname, 'media/high_pitch.mp3' if is_last else 'media/low_pitch.mp3'
  File "/root/mato/recorder_discord_bot/.venv/lib/python3.6/site-packages/discord/player.py", line 319, in __init__
    super().__init__(source, executable=executable, args=args, **subprocess_kwargs)
  File "/root/mato/recorder_discord_bot/.venv/lib/python3.6/site-packages/discord/player.py", line 133, in __init__
    self._process = self._spawn_process(args, **kwargs)
  File "/root/mato/recorder_discord_bot/.venv/lib/python3.6/site-packages/discord/player.py", line 142, in _spawn_process
    raise ClientException(executable + ' was not found.') from None
discord.errors.ClientException: ffmpeg was not found.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/root/mato/recorder_discord_bot/.venv/lib/python3.6/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "./bot.py", line 134, in on_message
    voice_client = await voice_channel_twin.connect()
  File "/root/mato/recorder_discord_bot/.venv/lib/python3.6/site-packages/discord/abc.py", line 1095, in connect
    raise ClientException('Already connected to a voice channel.')
discord.errors.ClientException: Already connected to a voice channel.

**Comment by tsrubar** [comment]
REsolved by installing ffmepg by [https://www.cloudbooklet.com/how-to-install-and-use-ffmpeg-on-centos-7/](https://www.cloudbooklet.com/how-to-install-and-use-ffmpeg-on-centos-7/)
